name: dev

on:
  push:
    branches: [dev]

  pull_request:
    branches: [dev]

jobs:
  build-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run build
      run: npm run build

    - name: Run lint
      run: npm run lint || echo "Lint warnings found"

    - name: Run npm audit
      run: npm audit --audit-level=moderate || echo "Vulnerabilities found"
